import React from 'react'
import Head from 'next/head'
import Slideshow from '../components/Slideshow'
import SplashView from '../components/SplashView'

export default function about() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>EUP NDC - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplashView splashHeader={'About'} />
    </div>
  )
}
