import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Slideshow from '../components/Slideshow'
import SplashView from '../components/SplashView'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import ScrollToPlugin from 'gsap/dist/ScrollToPlugin';
import gsap from "gsap"

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin)

const PicturePanel = () => {
  return (
    <div className="min-h-screen panel">
      <div className="w-full h-full absolute">
        <Image  src={'/panel-imgs/capabilities/rdte.png'} layout={"fill"} objectFit={"cover"}/>
      </div>
      <div className="w-full h-full absolute">
        <Image  src={'/panel-imgs/home/vignette.png'} layout={"fill"} objectFit={"cover"}/>
      </div>
    </div>
  )
}

const BigTextPanel = ({imageSrc, panelHeader}) => {
  return (
    <div className="min-h-screen panel">
      <div className="w-full h-full absolute">
        <Image  src={imageSrc} layout={"fill"} objectFit={"cover"}/>
      </div>
      <div className="absolute h-full w-full flex flex-col justify-center space-y-8">
        <div className="mx-auto font-['Ethnocentric'] text-8xl">{panelHeader}</div>
        <p className="mx-auto w-[600px] text-xl text-center">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit duis tristique sollicitudin. Et tortor at risus viverra adipiscing at in tellus. Suspendisse sed nisi lacus sed viverra tellus in hac. In hendrerit gravida rutrum quisque non tellus.
        </p>
      </div>
    </div>
  )
}

export default function capabilites() {
  const panelList = [
    <PicturePanel key={1}/>,
    <BigTextPanel imageSrc={'/panel-imgs/capabilities/research.png'} key={2} panelHeader={'Research'}/>,
    <BigTextPanel imageSrc={'/panel-imgs/capabilities/develop.png'} key={3} panelHeader={'Development'}/>, 
    <BigTextPanel imageSrc={'/panel-imgs/capabilities/testing.png'} key={4} panelHeader={'Testing'}/>, 
    <BigTextPanel imageSrc={'/panel-imgs/capabilities/eval.png'} key={5} panelHeader={'Evaluation'}/>, 
  ]

  return (
    <div className="flex flex-col">
      <Head>
        <title>EUP NDC - Capabilites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplashView splashHeader={'Capabilites'} imageSrc={'/panel-imgs/capabilities/splash.png'} />
      <Slideshow panels={panelList} overviewHeader={'RDT&E'} />
    </div>
  )
}
