import React from 'react'
import Head from 'next/head'

export default function capabilites() {
  return (
    <div className="min-h-[100vh] pt-[100px]">
      <Head>
        <title>EUP NDC - Capabilites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        Capabilites
    </div>
  )
}
