import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import ScrollToPlugin from 'gsap/dist/ScrollToPlugin';
import { useEffect } from 'react';


gsap.registerPlugin(ScrollTrigger, ScrollToPlugin)

const SplashView = () => {
  return (
    <div className="min-h-[840px] h-screen flex flex-col panel">
        <div className="h-4/6 bg-gray-500 overflow-hidden z-0">
          <video autoPlay muted loop className={styles.video}>         
            <source src="/temp-video.mp4" type="video/mp4"/>       
          </video>
          
        </div>
        <div className="z-10 h-2/6 bg-ndcDark">
         <div className="text-ndcWhite flex flex-col items-center h-full">
            <div className="h-[120px]  z-50 w-full absolute translate-y-[-64px]">
              <Image 
                src="/light-bar.png" 
                layout='fill'
                objectFit='contain'
              />
            </div>
            <p className='text-xl w-[682px] text-center	flex-grow flex items-center pb-24 '>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit duis tristique sollicitudin. Et tortor at risus viverra adipiscing at in tellus. Suspendisse sed nisi lacus sed viverra tellus in hac. In hendrerit gravida rutrum quisque non tellus.
            </p>
          
            <div className='h-4 w-12 absolute p-2 bottom-12 animate-bounce cursor-pointer'>
              <Image
                src="/arrow-down.png"
                layout='fill'
                objectFit='contain'
              />
            </div>
          </div>
        </div>
      </div>
  )
}

export default function Home() {
  const goToSection = (i, scrollTween) => {
    scrollTween = gsap.to(window, {
      scrollTo: {y: i * innerHeight, autoKill: false},
      duration: 1,
      onComplete: () => scrollTween = null,
      overwrite: true
    });
  }

  useEffect(() => {
    let panels =  gsap.utils.toArray('.panel'), scrollTween;

    panels.forEach((panel, i) => {
      ScrollTrigger.create({
        trigger: panel,
        start: "bottom bottom",
        end: "bottom bottom",
        onToggle: self => self.isActive && !scrollTween && goToSection(i, scrollTween)
      });
    });

    ScrollTrigger.create({
      start: 0, 
      end: "max",
      snap: 1 / (panels.length - 1)
    })
  }, [])

  return (
    <div className="flex flex-col text-ndcWhite">
      <Head>
        <title>EUP NDC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplashView />

      <div className='bg-red-500 h-screen panel flex flex-col bg-[url("/panel-imgs/home/space.png")] bg-cover'>
        <p className="font-['Ethnocentric'] text-4xl self-center relative top-24 z-30">All Domain Warfare</p>
        <div className="absolute bg-[url('/panel-imgs/home/vignette.png')] w-full h-full bg-cover" />  
        <div className="absolute z-30 h-full w-full flex justify-start items-center">
          <p className="-rotate-90 text-5xl font-thin tracking-[1.25rem]">Space</p>
        </div> 
      </div>


      <div className='bg-yellow-500 h-screen panel flex flex-col bg-[url("/panel-imgs/home/air.png")] bg-cover'>
        <div className="absolute bg-[url('/panel-imgs/home/vignette.png')] w-full h-full bg-cover" />  
        <p className="font-['Ethnocentric'] text-4xl self-center relative top-24 z-30">All Domain Warfare</p>
      </div>


      <div className='bg-green-500 h-screen panel flex flex-col bg-[url("/panel-imgs/home/cyber.png")] bg-cover'>
        <div className="absolute bg-[url('/panel-imgs/home/vignette.png')] w-full h-full bg-cover" />  
        <p className="font-['Ethnocentric'] text-4xl self-center relative top-24 z-30">All Domain Warfare</p>
      </div>

      <div className='bg-green-500 h-screen panel flex flex-col bg-[url("/panel-imgs/home/land.png")] bg-cover'>
        <div className="absolute bg-[url('/panel-imgs/home/vignette.png')] w-full h-full bg-cover" />  
        <p className="font-['Ethnocentric'] text-4xl self-center relative top-24 z-30">All Domain Warfare</p>
      </div>

      <div className='bg-green-500 h-screen panel flex flex-col bg-[url("/panel-imgs/home/maritime.png")] bg-cover'>
        <div className="absolute bg-[url('/panel-imgs/home/vignette.png')] w-full h-full bg-cover" />  
        <p className="font-['Ethnocentric'] text-4xl self-center relative top-24 z-30">All Domain Warfare</p>
      </div>
    </div>
  )
}
