import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react';
import Slideshow from '../components/Slideshow'
import SplashView from '../components/SplashView'


const Panel = ({backgroundImage, symbolImage, sideText}) => {
  const sideref = useRef(null)
  const [sideWidth, setWidth] = useState(0)
  useEffect(() => {
    setWidth(sideref.current.clientWidth)
  }, [sideref])
  return (
    <div className="panel">
      <div className="w-full h-full absolute">
        <Image  src={backgroundImage} layout={"fill"} objectFit={"cover"}/>
      </div>
      <div className="w-full h-full absolute">
        <Image  src={'/panel-imgs/home/vignette.png'} layout={"fill"} objectFit={"cover"}/>
      </div>
      <div className="min-h-screen">
        <div className="absolute w-full h-full flex  items-center">
          <p ref={sideref} style={{marginTop: sideWidth}} className={`fixed left-0 origin-top-left ml-2 md:ml-8 -translate-x-8  -rotate-90 flex md:text-3xl lg:text-5xl font-thin tracking-[1.25rem] panel-category opacity-0 uppercase drop-shadow-md`}>{sideText}</p>
        </div>
        <div className='absolute w-full h-full '>
          <div className="mx-auto px-8 lg:w-[64rem] h-full flex flex-col justify-center translate-y-16 md:translate-y-0">
            <div className="flex flex-col panel-content md:mb-32">
              <div className="p-16 md:p-56 md:translate-y-16">
                <div className="w-full aspect-square relative top-8 md:top-0">
                  <Image
                    src={symbolImage}
                    layout='fill'
                    objectFit='contain'
                    style={{filter: "drop-shadow(0px 0px 30px #878787)"}}
                  />
                </div>
              </div>
              <div className="relative flex flex-col mb-24 md:mb-0">
                <div className="text-sm md:text-xl p-4 md:p-0 text-center mb-4 drop-shadow-md">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit duis tristique sollicitudin. Et tortor at risus viverra adipiscing at in tellus. Suspendisse sed nisi lacus sed viverra tellus in hac. In hendrerit gravida rutrum quisque non tellus.</div>
                  
                <div className="z-50 w-full relative pt-8">
                    <Image 
                      src="/light-bar-white.png" 
                      layout='fill'
                      objectFit='contain'
                    />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function Home() {
  const panelList = [
    <Panel key={1} sideText={'space'} backgroundImage={'/panel-imgs/home/space.png'} symbolImage={"/panel-symbols/home/satelite.png"}/>,
    <Panel key={2} sideText={'air'} backgroundImage={'/panel-imgs/home/air.png'} symbolImage={"/panel-symbols/home/drone.png"}/>,
    <Panel key={3} sideText={'cyber'} backgroundImage={'/panel-imgs/home/cyber.png'} symbolImage={"/panel-symbols/home/cyber.png"}/>,
    <Panel key={4} sideText={'land'} backgroundImage={'/panel-imgs/home/land.png'} symbolImage={"/panel-symbols/home/land.png"}/>,
    <Panel key={5} sideText={'maritime'} backgroundImage={'/panel-imgs/home/maritime.png'} symbolImage={"/panel-symbols/home/maritime.png"}/>,
  ]
  return (
    <div className="flex flex-col text-ndcWhite">
      <Head>
        <title>EUP NDC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplashView videoSrc={"/temp-video.mp4"}/>
      <Slideshow panels={panelList} overviewHeader={'All Domain Warfare'}/>
    </div>
  )
}